export const salesData = [
  {
    name: "Jan",
    Sales: 4000,
  },
  {
    name: "Feb",
    Sales: 3000,
  },
  {
    name: "Mar",
    Sales: 8000,
  },
  {
    name: "Apr",
    Sales: 7000,
  },
  {
    name: "May",
    Sales: 5000,
  },
  {
    name: "Jun",
    Sales: 4000,
  },
  {
    name: "Jul",
    Sales: 9000,
  },
  {
    name: "Aug",
    Sales: 10000,
  },
  {
    name: "Sep",
    Sales: 4000,
  },
  {
    name: "Oct",
    Sales: 8000,
  },
  {
    name: "Nov",
    Sales: 11000,
  },
  {
    name: "Dec",
    Sales: 14000,
  },
];

export const userRows = [
  {
    id: 1,
    userName: "Jon Snow",
    avatar:
      "https://i2.wp.com/www.cssscript.com/wp-content/uploads/2020/12/Customizable-SVG-Avatar-Generator-In-JavaScript-Avataaars.js.png?fit=438%2C408&ssl=1",
    email: "jon@co.com",
    status: "Active",
    transaction: "$5,000",
  },
  {
    id: 2,
    userName: "Jon Snow",
    avatar: "",
    email: "",
    status: "",
    transaction: "",
  },
  {
    id: 3,
    userName: "Jon Snow",
    avatar: "",
    email: "",
    status: "",
    transaction: "",
  },
  {
    id: 4,
    userName: "Jon Snow",
    avatar: "",
    email: "",
    status: "",
    transaction: "",
  },
  {
    id: 5,
    userName: "Jon Snow",
    avatar: "",
    email: "",
    status: "",
    transaction: "",
  },
  {
    id: 6,
    userName: "Jon Snow",
    avatar: "",
    email: "",
    status: "",
    transaction: "",
  },
  {
    id: 7,
    userName: "Jon Snow",
    avatar: "",
    email: "",
    status: "",
    transaction: "",
  },
  {
    id: 8,
    userName: "Jon Snow",
    avatar: "",
    email: "",
    status: "",
    transaction: "",
  },
  {
    id: 9,
    userName: "Jon Snow",
    avatar: "",
    email: "",
    status: "",
    transaction: "",
  },
  {
    id: 10,
    userName: "Jon Snow",
    avatar: "",
    email: "",
    status: "",
    transaction: "",
  },
  {
    id: 11,
    userName: "Jon Snow",
    avatar: "",
    email: "",
    status: "",
    transaction: "",
  },
];
export const productRows = [
  {
    id: 1,
    name: "Test Product",
    img: "https://i2.wp.com/www.cssscript.com/wp-content/uploads/2020/12/Customizable-SVG-Avatar-Generator-In-JavaScript-Avataaars.js.png?fit=438%2C408&ssl=1",
    stock: 250,
    status: "Active",
    price: "$5,000",
  },
  {
    id: 2,
    name: "Test Product",
    img: "https://i2.wp.com/www.cssscript.com/wp-content/uploads/2020/12/Customizable-SVG-Avatar-Generator-In-JavaScript-Avataaars.js.png?fit=438%2C408&ssl=1",
    stock: 250,
    status: "Active",
    price: "$5,000",
  },
  {
    id: 3,
    name: "Test Product",
    img: "https://i2.wp.com/www.cssscript.com/wp-content/uploads/2020/12/Customizable-SVG-Avatar-Generator-In-JavaScript-Avataaars.js.png?fit=438%2C408&ssl=1",
    stock: 250,
    status: "Active",
    price: "$5,000",
  },
  {
    id: 4,
    name: "Test Product",
    img: "https://i2.wp.com/www.cssscript.com/wp-content/uploads/2020/12/Customizable-SVG-Avatar-Generator-In-JavaScript-Avataaars.js.png?fit=438%2C408&ssl=1",
    stock: 250,
    status: "Active",
    price: "$5,000",
  },
  {
    id: 5,
    name: "Test Product",
    img: "https://i2.wp.com/www.cssscript.com/wp-content/uploads/2020/12/Customizable-SVG-Avatar-Generator-In-JavaScript-Avataaars.js.png?fit=438%2C408&ssl=1",
    stock: 250,
    status: "Active",
    price: "$5,000",
  },
  {
    id: 6,
    name: "Test Product",
    img: "https://i2.wp.com/www.cssscript.com/wp-content/uploads/2020/12/Customizable-SVG-Avatar-Generator-In-JavaScript-Avataaars.js.png?fit=438%2C408&ssl=1",
    stock: 250,
    status: "Active",
    price: "$5,000",
  },
  {
    id: 7,
    name: "Test Product",
    img: "https://i2.wp.com/www.cssscript.com/wp-content/uploads/2020/12/Customizable-SVG-Avatar-Generator-In-JavaScript-Avataaars.js.png?fit=438%2C408&ssl=1",
    stock: 250,
    status: "Active",
    price: "$5,000",
  },
  {
    id: 8,
    name: "Test Product",
    img: "https://i2.wp.com/www.cssscript.com/wp-content/uploads/2020/12/Customizable-SVG-Avatar-Generator-In-JavaScript-Avataaars.js.png?fit=438%2C408&ssl=1",
    stock: 250,
    status: "Active",
    price: "$5,000",
  },
  {
    id: 9,
    name: "Test Product",
    img: "https://i2.wp.com/www.cssscript.com/wp-content/uploads/2020/12/Customizable-SVG-Avatar-Generator-In-JavaScript-Avataaars.js.png?fit=438%2C408&ssl=1",
    stock: 250,
    status: "Active",
    price: "$5,000",
  },
  {
    id: 10,
    name: "Test Product",
    img: "https://i2.wp.com/www.cssscript.com/wp-content/uploads/2020/12/Customizable-SVG-Avatar-Generator-In-JavaScript-Avataaars.js.png?fit=438%2C408&ssl=1",
    stock: 250,
    status: "Active",
    price: "$5,000",
  },
];
